import mammoth from "mammoth";
import type { SupportedFileKind } from "../files/file-validation";

export interface ExtractedSegment {
  text: string;
  /** 1-based page number. Only set for PDF — other formats have no fixed page concept. */
  pageNumber?: number;
}

/**
 * Extracts text from a file buffer according to its kind, returning one
 * segment per page for PDFs (so each chunk can be attributed to an
 * exact page — see chunking in document-processing.service.ts) and a
 * single segment for formats with no page concept (TXT, Markdown,
 * DOCX).
 *
 * Throws on malformed/corrupt content (e.g. a file whose magic number
 * matched at upload time but whose body doesn't actually parse) — the
 * caller (DocumentProcessingService) is responsible for catching this
 * and marking the file `status = "failed"`.
 */
export async function extractSegments(kind: SupportedFileKind, buffer: Buffer): Promise<ExtractedSegment[]> {
  switch (kind) {
    case "txt":
    case "md":
      return extractPlainText(buffer);
    case "pdf":
      return extractPdf(buffer);
    case "docx":
      return extractDocx(buffer);
  }
}

function extractPlainText(buffer: Buffer): ExtractedSegment[] {
  // Strip a UTF-8 BOM if present; otherwise take the bytes as UTF-8 as-is.
  const text = buffer.toString("utf-8").replace(/^\uFEFF/, "");
  return [{ text }];
}

/**
 * Uses `pdfjs-dist` (Mozilla's actively-maintained PDF.js), not the
 * long-unmaintained `pdf-parse` package — `pdf-parse`'s bundled pdf.js
 * build (from ~2015) failed to parse ordinary, non-exotic PDFs
 * generated by multiple different real-world tools when tested against
 * this project's Node.js version, throwing "bad XRef entry" even for
 * simple single-page documents. `pdfjs-dist` handled every test PDF
 * (PDFKit-, ReportLab-, and LibreOffice-generated) correctly.
 *
 * Text extraction quality still depends on how the source PDF embeds
 * its font/glyph-to-Unicode mapping: PDFs from some generators (a
 * WebKit-based one was observed during testing) do not embed a proper
 * ToUnicode CMap and so extract as mojibake even though pdf.js parses
 * the file structure without error. This is a general PDF-format
 * limitation, not specific to this implementation — there is no
 * reliable way to detect it up front, and later phases may need a
 * fallback (e.g. OCR) for affected documents.
 */
async function extractPdf(buffer: Buffer): Promise<ExtractedSegment[]> {
  const pdfjsLib = await import("pdfjs-dist/legacy/build/pdf.mjs");
  const uint8 = new Uint8Array(buffer);

  const loadingTask = pdfjsLib.getDocument({
    data: uint8,
    // Suppresses noisy console warnings from pdf.js's own logger for
    // conditions (like missing standard-font glyph data) that don't
    // affect text extraction, only visual rendering, which this
    // service never does.
    verbosity: 0,
  });

  const doc = await loadingTask.promise;
  try {
    const segments: ExtractedSegment[] = [];
    for (let pageNumber = 1; pageNumber <= doc.numPages; pageNumber++) {
      const page = await doc.getPage(pageNumber);
      try {
        const content = await page.getTextContent();
        const text = content.items.map((item) => ("str" in item ? item.str : "")).join("");
        segments.push({ text, pageNumber });
      } finally {
        page.cleanup();
      }
    }
    return segments;
  } finally {
    await loadingTask.destroy();
  }
}

async function extractDocx(buffer: Buffer): Promise<ExtractedSegment[]> {
  const result = await mammoth.extractRawText({ buffer });
  return [{ text: result.value }];
}
